# Generated by Django 3.2.5 on 2021-07-07 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('middlename', models.CharField(max_length=50, null=True)),
                ('user_type', models.IntegerField(blank=True, choices=[('LEAD_DESIGNER', 0), ('LEAD_TECHNOLOGIST', 1), ('SOFTWARE_ENGINEER', 2), ('PRODUCTION_MANAGER', 3), ('LABOR_RATING_ENGINEER', 4), ('FOREMAN', 5), ('TECHNICAL_DOCUMENTATION_OFFICER', 6)], null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
