version: '3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  migration:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/app
    links:
      - db
    depends_on:
      - db
      - web

  db:
    image: mysql:5.7
    restart: always
    ports:
      - 33306:3306
    environment:
      MYSQL_DATABASE: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
