version: '3'

services:
    web:
        build: .
        volumes:
            - ./:/signal_project/
        ports:
            - 8000:8000
        environment:
            - SECRET_KEY=foo
            - DEBUG=1
            - SQL_ENGINE=django.db.backends.postgresql
            - SQL_DATABASE=dbase
            - SQL_USER=admin
            - SQL_PASSWORD=admin
            - SQL_HOST=db
            - SQL_PORT=5432
            - DATABASE=postgres
        depends_on:
            - db

    db:
        image: postgres
        volumes:
            - ./postgres_data:/var/lib/postgresql
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=dbase

volumes:
    postgres_data:
