# Generated by Django 3.2.5 on 2021-07-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decimal_number', models.CharField(help_text='Децимальный номер', max_length=50, null=True)),
                ('name', models.CharField(help_text='Наименование', max_length=100)),
                ('entry_number', models.CharField(help_text='Входимость', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decimal_number', models.CharField(help_text='Децимальный номер', max_length=50, null=True)),
                ('name', models.CharField(help_text='Наименование', max_length=500)),
                ('entry_number', models.CharField(help_text='Первичная входимость', max_length=100, null=True)),
                ('count_number', models.CharField(help_text='Количество', max_length=200)),
                ('product_type', models.IntegerField(choices=[('ASSEMBLY', 0), ('DETAIL', 1), ('STANDARD_PRODUCTS', 2), ('OTHER_PRODUCTS', 3)], help_text='Тип изделия')),
            ],
        ),
    ]
