# Generated by Django 3.2.5 on 2021-07-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='decimal_number',
            field=models.CharField(help_text='Децимальный номер', max_length=300, null=True),
        ),
    ]
